---
title: "{{< var course.short >}} - Course Learning Objectives"
editor: 
  markdown: 
    wrap: 80
---

## Official Course Description

This course provides an understanding of the principles and concepts of using
computer tools for data analysis and visualization. Students will learn to use a
scientific programming language (such as `R`) to import and export data from and
into spreadsheets or other statistical software packages. They will gain
experience in analyzing both quantitative and qualitative data, and statistical
modelling techniques will be introduced. Written reports will prepare students
for clear communication of their analysis in professional settings. This course
is designed primarily for Masters' students in statistics and quantitative
methods and modeling (QMM), and those interested in carrying out sophisticated
statistical analyses of data using statistical software.

## Program Learning Goals

This course contributes to the [program learning
goals](https://zicklin.baruch.cuny.edu/faculty-research/faculty-staff/assurance-of-learning/)
of several MS programs offered by the Zicklin School of Business.

### MS in Business Analytics

This course contributes to the following Program Learning Goals for the MS in
Business Analytics:

| {{< var course.short >}} Learning Goal |               MSBA Learning Goal               | Description                                                                                                                                                                                                          |
|:-------------------------------------------------------:|:---------------------------------------:|:-------------------------------------------------------------|
|                 **✓**                  |                Data Management                 | Students will be able to apply methods, tools, and software for acquiring, managing/storing, and accessing structured and unstructured data. Students will also demonstrate knowledge of the strategic uses of data. |
|                 **✓**                  | Foundational Statistical / Quantitative Skills | Students will be able to prepare data for statistical analysis, perform basic exploratory and descriptive analysis as well as employ foundational statistical techniques needed to analyze data.                     |
|                 **✓**                  |    Advanced Statistical/Quantitative Skills    | Students will be able to build and interpret advanced predictive models. Students will be able to combine business rules and mathematical models to optimize business decisions from data.                           |
|                                        |               Ethical Awareness                | Students will be able to articulate an understanding of ethical issues in all phases of business analytics with particular emphasis on the new possibilities afforded by the emergence of big data.                  |
|                 **✓**                  |           Professional Communication           | Students will be able to explain complex analytical models and their results orally and in writing to technical and non technical/lay audiences.                                                                     |
|                 **✓**                  |             Knowledge Integration              | Students will be able to apply the three key types of analytics (descriptive, predictive, and prescriptive) in a business domain to add value to business decision-making.                                           |

: MSBA Program Learning Goals

### MS in Quantitative Methods & Modeling

This course contributes to the following Program Learning Goals for the MS in
Quantitative Methods & Modeling:

| {{< var course.short >}} Learning Goal |             MSQMM Learning Goal             | Description                                                                                                                                                                                                 |
|:----------------------------------------------------:|:--------------------------------------:|:------------------------------------------------------------|
|                 **✓**                  | Operations Research & Mathematical Modeling | Students will be able to effectively model, evaluate, and solve quantitative (business) problems using quantitative modeling methods (e.g. deterministic and probabilistic operations research techniques). |
|                 **✓**                  |                 Statistics                  | Students will be able to correctly apply appropriate statistical methods when defining, solving, and analyzing problems.                                                                                    |
|                 **✓**                  |            Technology Competency            | Students will be able to use current technological tools, including spreadsheets and specialized software, when solving problems.                                                                           |
|                 **✓**                  |         Professional Communication          | Students will be able to effectively communicate their problem solving methods and solutions to technical and non-technical audiences.                                                                      |

: MSQMM Program Learning Goals

### MS in Statistics

This course contributes to the following Program Learning Goals for the MS in
Statistics:

| {{< var course.short >}} Learning Goal |     MS Stat Learning Goal      | Description                                                                                                                                                                                                                                                                                                                          |
|:----------------------------------------------------:|:------------------------------------------------:|:-----------------------------------------------------------|
|                 **✓**                  | General Statistical Competence | Students will be able to apply appropriate probability models and statistical techniques when analyzing problems from business and other fields.                                                                                                                                                                                     |
|                 **✓**                  |      Statistical Practice      | Students will become familiar with the standard tools of statistical practice for multiple regression, along with the tools of a subset of specialized statistical areas such as multivariate analysis, applied sampling, time series analysis, experimental design, data mining, categorical analysis, and/or stochastic processes. |
|                 **✓**                  |     Technology Competency      | Students will learn to use one or more of the benchmark statistical software platforms, such as SAS or R.                                                                                                                                                                                                                            |

: MS Statistics Program Learning Goals
